### ISSUE TITLE
Module Loader

### ISSUE THREAD

**Issue by ChiefORZ** [ryanflorence/react-magic-move#12]
Yes, you might be asking yourself 'what??? there are people out there not using Module Loaders?'. But yeah, you are correct. I am not using RequireJS or any similar Environment.

And correct me if i'm wrong, for this - lets call it Component - a Module Loader is required, because i am getting the Error - Uncaught ReferenceError: MagicMove is not defined

This Library seems freaking awesome, i would love to give it a try :)

thanks for the help

**Comment by NgoKnows** [comment]
I am having this same problem! Any help would be much appreciated!
